import Link from "next/link";
import { Suspense } from "react";
import { ArrowUpRight } from "lucide-react";
import { AuthForm } from "@/components/auth-form";

export function AuthPage({ mode }: { mode: "login" | "register" }) {
  const register = mode === "register";
  return <main className="grid min-h-[calc(100vh-5rem)] lg:grid-cols-[.95fr_1.05fr]"><section className="relative flex min-h-56 flex-col justify-between overflow-hidden bg-[var(--navy)] p-6 text-[var(--paper)] sm:p-10 lg:min-h-[650px] lg:p-14"><div aria-hidden="true" className="poster-grid absolute inset-0 opacity-25" /><div className="relative"><p className="eyebrow text-[var(--accent)]">EventHub / Acesso</p><h1 className="display-tight mt-6 max-w-xl text-[clamp(2.7rem,5.5vw,5.8rem)] font-extrabold">{register ? <>O próximo encontro começa <span className="text-[var(--accent)]">aqui.</span></> : <>Volte para o que acontece <span className="text-[var(--accent)]">lá fora.</span></>}</h1><p className="mt-5 max-w-md text-base text-white/65">{register ? "Crie sua conta para reservar ingressos ou publicar seu próximo evento." : "Seus ingressos, eventos e boas histórias continuam à sua espera."}</p></div><div className="relative mt-8 hidden max-w-sm rotate-[-3deg] border-[6px] border-[var(--paper)] lg:block"><img src="/demo-covers/festival-aurora.png" alt="" className="aspect-[16/9] w-full object-cover" /><span className="poster-label absolute -bottom-4 -right-4 bg-[var(--accent)] text-[var(--navy)]">Presença confirmada</span></div></section><section className="flex items-center justify-center px-5 py-10 sm:px-10 lg:py-16"><div className="w-full max-w-md"><p className="eyebrow text-[var(--primary)]">{register ? "Comece agora / 01" : "Sua conta / 02"}</p><h2 className="display-tight mt-3 text-4xl font-extrabold sm:text-5xl">{register ? "Crie sua conta." : "Que bom ter você de volta."}</h2><p className="mt-4 text-slate-600">{register ? "É rápido. O melhor acontece depois." : "Entre e continue de onde parou."}</p><div className="mt-8"><Suspense><AuthForm mode={mode} /></Suspense></div><p className="mt-6 text-sm text-slate-600">{register ? "Já tem conta?" : "Ainda não tem conta?"} <Link className="inline-flex items-center gap-1 font-extrabold text-[var(--primary)] hover:underline" href={register ? "/entrar" : "/cadastro"}>{register ? "Entrar" : "Cadastre-se"}<ArrowUpRight className="size-4" /></Link></p>{!register && process.env.NODE_ENV !== "production" && <p className="mt-6 border border-[var(--border)] p-3 text-xs text-slate-600"><strong>Conta de demonstração local:</strong> participante@eventhub.dev / Demo@123</p>}</div></section></main>;
}
