import Link from "next/link";
import { ArrowUpRight, CheckCircle2, QrCode, Ticket, Users } from "lucide-react";
import { EventActions } from "@/components/event-actions";
import { MetricsChart } from "@/components/metrics-chart";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { authenticatedGet } from "@/lib/server-api";
import type { EventView, Metrics, PageView } from "@/lib/types";
import { formatDate } from "@/lib/utils";

interface Attendee { registrationId: string; ticketId: string; ticketTypeName: string; name: string; email: string; status: string; registeredAt: string; }
export default async function EventDashboard({ params }: { params: Promise<{ id: string }> }) {
  const id = (await params).id;
  const all = await authenticatedGet<EventView[]>("events/organizer/mine", `/organizador/eventos/${id}`);
  const event = all.find((item) => item.id === id);
  if (!event) return <main className="container-shell py-14"><h1 className="text-3xl font-extrabold">Evento não encontrado</h1></main>;
  const [metrics, attendees] = await Promise.all([authenticatedGet<Metrics>(`organizer/events/${id}/metrics`, `/organizador/eventos/${id}`), authenticatedGet<PageView<Attendee>>(`organizer/events/${id}/attendees?page=0&size=25`, `/organizador/eventos/${id}`)]);
  const summary = [["Inscritos", metrics.confirmed, Users], ["Capacidade", metrics.capacity, Ticket], ["Check-ins", metrics.checkedIn, CheckCircle2], ["Taxa de entrada", `${metrics.checkInRate}%`, QrCode]] as const;
  return <main className="container-shell py-8 sm:py-12"><section className="relative overflow-hidden bg-[var(--navy)] p-6 text-[var(--paper)] sm:p-10"><div aria-hidden="true" className="poster-grid absolute inset-0 opacity-25" /><div className="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-3"><Badge className={event.status === "DRAFT" ? "bg-amber-100 text-amber-900" : event.status === "CANCELLED" ? "bg-red-100 text-red-800" : ""}>{event.status === "DRAFT" ? "Rascunho" : event.status === "CANCELLED" ? "Cancelado" : "Publicado"}</Badge><span className="eyebrow text-white/60">{formatDate(event.startsAt)}</span></div><h1 className="display-tight mt-5 text-4xl font-extrabold sm:text-6xl">{event.title}<span className="text-[var(--primary)]">.</span></h1><p className="mt-4 text-white/60">{event.venue} · {event.city}, {event.state}</p></div><div className="flex flex-wrap gap-2"><EventActions eventId={event.id} status={event.status} />{event.status === "PUBLISHED" && <Link href={`/organizador/eventos/${id}/check-in`} className={buttonVariants({ variant: "primary" })}><QrCode className="size-4" /> Abrir scanner</Link>}</div></div></section>
    <section aria-label="Métricas do evento" className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{summary.map(([label, value, Icon], index) => <div className={`border p-5 ${index === 0 ? "border-[var(--navy)] bg-[var(--accent)]" : "border-[var(--border)] bg-[var(--surface)]"}`} key={label}><Icon className="size-6" /><p className="mt-5 font-display text-4xl font-extrabold tracking-[-.06em]">{value}</p><p className="eyebrow mt-1 text-slate-600">{label}</p></div>)}</section>
    {!!metrics.byType?.length && <section className="mt-8"><div className="border-b border-[var(--navy)] pb-3"><p className="eyebrow text-[var(--primary)]">Por tipo de ingresso</p><h2 className="mt-1 font-display text-2xl font-extrabold">Ocupação em tempo real</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{metrics.byType.map((type) => <div key={type.ticketTypeId} className="border border-[var(--border)] bg-[var(--surface)] p-5"><h3 className="font-display text-xl font-extrabold">{type.name}</h3><p className="mt-3 text-sm text-slate-600">{type.confirmed} de {type.capacity} ingressos · {type.checkedIn} check-ins</p><div className="mt-3 h-1 bg-[var(--surface-muted)]"><div className="h-full bg-[var(--primary)]" style={{ width: `${Math.min(100, Math.round(type.confirmed / Math.max(1, type.capacity) * 100))}%` }} /></div></div>)}</div></section>}
    <section className="mt-8 grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="min-w-0 border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-7"><p className="eyebrow text-[var(--primary)]">Movimento</p><h2 className="mt-2 font-display text-2xl font-extrabold">Ingressos nos últimos 7 dias</h2><p className="text-sm text-slate-600">Evolução diária de ingressos emitidos.</p><div className="mt-5"><MetricsChart data={metrics.registrationsByDay} /></div></div><div className="min-w-0 border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] p-5 sm:p-7"><p className="eyebrow text-[var(--primary)]">Pessoas</p><h2 className="mt-2 font-display text-2xl font-extrabold">Participantes recentes</h2><p className="text-sm text-slate-600">{attendees.totalElements} {attendees.totalElements === 1 ? "ingresso" : "ingressos"} no total</p><Link href={`/organizador/eventos/${id}/inscritos`} className="mt-4 inline-flex items-center gap-1 text-sm font-extrabold text-[var(--primary)] hover:underline">Ver todos os inscritos <ArrowUpRight className="size-4" /></Link></div><div className="divide-y divide-[var(--border)]">{attendees.content.slice(0, 6).map((person) => <div key={person.ticketId ?? person.registrationId} className="flex items-center justify-between gap-3 px-5 py-4 sm:px-7"><div className="min-w-0"><p className="truncate font-bold">{person.name}</p><p className="truncate text-sm text-slate-600">{person.ticketTypeName ?? "Ingresso geral"} · {person.email}</p></div><Badge className={person.status === "CANCELLED" ? "bg-red-100 text-red-800" : ""}>{person.status === "CONFIRMED" ? "Confirmado" : "Cancelado"}</Badge></div>)}</div></div></section>
  </main>;
}
