import Link from "next/link";
import { ArrowUpRight, CalendarDays, MapPin, QrCode } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { WaitlistCard } from "@/components/waitlist-card";
import { authenticatedGet } from "@/lib/server-api";
import type { TicketView, WaitlistView } from "@/lib/types";
import { formatDate } from "@/lib/utils";

export const metadata = { title: "Meus ingressos" };
export default async function MyTicketsPage() {
  const [tickets, waitlist] = await Promise.all([authenticatedGet<TicketView[]>("tickets/mine"), authenticatedGet<WaitlistView[]>("waitlist/mine")]);
  return <main><section className="relative overflow-hidden bg-[var(--navy)] text-[var(--paper)]"><div aria-hidden="true" className="poster-grid absolute inset-0 opacity-25" /><div className="container-shell relative flex flex-col gap-6 py-12 sm:flex-row sm:items-end sm:justify-between sm:py-16"><div><p className="eyebrow text-[var(--accent)]">Sua agenda / Seus encontros</p><h1 className="display-tight mt-3 text-5xl font-extrabold sm:text-6xl">Meus ingressos<span className="text-[var(--primary)]">.</span></h1><p className="mt-4 max-w-xl text-white/65">Tudo o que você precisa para chegar e viver a experiência.</p></div><Link className="focus-ring inline-flex min-h-11 items-center gap-2 border-b border-[var(--accent)] font-extrabold text-[var(--accent)]" href="/#eventos">Encontrar eventos <ArrowUpRight className="size-5" /></Link></div></section>
    <div className="container-shell py-10 sm:py-14">{waitlist.length > 0 && <section className="mb-12"><div className="border-b border-[var(--navy)] pb-4"><p className="eyebrow text-[var(--primary)]">A caminho</p><h2 className="mt-2 text-3xl font-extrabold">Lista de espera</h2></div><div className="mt-5 grid gap-5 lg:grid-cols-2">{waitlist.map((request) => <WaitlistCard key={request.id} request={request} />)}</div></section>}
      {tickets.length ? <section><div className="flex items-end justify-between gap-4 border-b border-[var(--navy)] pb-4"><div><p className="eyebrow text-[var(--primary)]">Presença confirmada</p><h2 className="mt-2 text-3xl font-extrabold">Prontos para apresentar</h2></div><span className="eyebrow text-slate-600">{tickets.length} {tickets.length === 1 ? "ingresso" : "ingressos"}</span></div><div className="mt-5 grid gap-5 lg:grid-cols-2">{tickets.map((ticket) => <Link key={ticket.id} href={`/ingressos/${ticket.id}`} className="focus-ring lift-card group grid overflow-hidden border border-[var(--border)] bg-[var(--surface)] sm:grid-cols-[180px_1fr]"><div className="event-image min-h-44">{ticket.coverUrl && <img src={ticket.coverUrl} alt="" className="h-full w-full object-cover" />}</div><div className="flex flex-col justify-between p-5"><div><div className="flex items-start justify-between gap-3"><Badge className={ticket.status === "ACTIVE" && ticket.eventStatus === "PUBLISHED" ? "" : "bg-red-100 text-red-800"}>{ticket.status === "ACTIVE" && ticket.eventStatus === "PUBLISHED" ? "Confirmado" : "Cancelado"}</Badge><QrCode className="size-5 text-[var(--primary)]" /></div><h3 className="mt-4 font-display text-2xl font-extrabold leading-tight tracking-[-.05em]">{ticket.eventTitle}</h3><p className="mt-1 text-sm font-bold text-slate-700">{ticket.attendeeName ?? "Participante"} · {ticket.ticketTypeName ?? "Ingresso geral"}</p></div><div className="mt-5 border-t border-[var(--border)] pt-3 text-sm text-slate-600"><p className="flex items-center gap-2"><CalendarDays className="size-4 text-[var(--primary)]" />{formatDate(ticket.startsAt)}</p><p className="mt-1 flex items-center gap-2"><MapPin className="size-4 text-[var(--primary)]" />{ticket.venue} · {ticket.city}</p></div></div></Link>)}</div></section> : !waitlist.length && <div className="grid min-h-72 place-items-center border border-[var(--border)] bg-[var(--surface)] p-8 text-center"><div><QrCode className="mx-auto size-10 text-[var(--primary)]" /><h2 className="mt-4 font-display text-2xl font-extrabold">Sua próxima história começa aqui.</h2><p className="mt-2 text-slate-600">Explore a agenda e escolha um evento para viver.</p><Link href="/#eventos" className="focus-ring mt-6 inline-flex min-h-11 items-center gap-2 bg-[var(--accent)] px-5 font-extrabold">Explorar agenda <ArrowUpRight className="size-4" /></Link></div></div>}
    </div>
  </main>;
}
