import Link from "next/link";
import { ArrowUpRight, CalendarPlus, MapPin, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { authenticatedGet } from "@/lib/server-api";
import type { EventView } from "@/lib/types";
import { formatShortDate } from "@/lib/utils";

export const metadata = { title: "Painel do organizador" };
const statusLabel = { DRAFT: "Rascunho", PUBLISHED: "Publicado", CANCELLED: "Cancelado", COMPLETED: "Concluído" };
export default async function OrganizerEventsPage() {
  const events = await authenticatedGet<EventView[]>("events/organizer/mine");
  return <main className="container-shell py-8 sm:py-12"><section className="poster-grid relative overflow-hidden bg-[var(--navy)] p-6 text-[var(--paper)] sm:p-10"><div className="relative flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-[var(--accent)]">Backstage / Organização</p><h1 className="display-tight mt-3 text-4xl font-extrabold sm:text-6xl">Seus eventos<span className="text-[var(--primary)]">.</span></h1><p className="mt-4 max-w-xl text-white/65">Acompanhe inscrições, cuide da entrada e faça tudo acontecer.</p></div><Link href="/organizador/eventos/novo" className={buttonVariants({ variant: "primary", size: "lg" })}><CalendarPlus className="size-5" /> Criar evento</Link></div></section><div className="mt-10 flex items-end justify-between border-b border-[var(--navy)] pb-4"><div><p className="eyebrow text-[var(--primary)]">Painel / Agenda</p><h2 className="mt-2 font-display text-2xl font-extrabold">Em suas mãos</h2></div><span className="eyebrow text-slate-600">{events.length} {events.length === 1 ? "evento" : "eventos"}</span></div><div className="mt-5 grid gap-4">{events.map((event) => <Link key={event.id} href={`/organizador/eventos/${event.id}`} className="focus-ring lift-card group grid gap-4 border border-[var(--border)] bg-[var(--surface)] p-4 sm:grid-cols-[140px_minmax(0,1fr)_auto] sm:items-center"><div className="event-image aspect-[16/10] overflow-hidden sm:aspect-[4/3]">{event.coverUrl && <img src={event.coverUrl} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge className={event.status === "DRAFT" ? "bg-amber-100 text-amber-900" : event.status === "CANCELLED" ? "bg-red-100 text-red-800" : ""}>{statusLabel[event.status]}</Badge><span className="eyebrow text-slate-500">{formatShortDate(event.startsAt)}</span></div><h3 className="mt-3 font-display text-2xl font-extrabold leading-tight tracking-[-.05em]">{event.title}</h3><p className="mt-2 flex items-center gap-1.5 text-sm text-slate-600"><MapPin className="size-4 text-[var(--primary)]" />{event.city}, {event.state}</p><p className="mt-3 flex items-center gap-1.5 text-sm font-bold"><Users className="size-4 text-[var(--primary)]" />{event.confirmedCount} de {event.capacity} ingressos ativos</p></div><span className="hidden size-10 place-items-center border border-[var(--navy)] transition group-hover:bg-[var(--accent)] sm:grid"><ArrowUpRight className="size-5" /></span></Link>)}{!events.length && <div className="border border-[var(--border)] bg-[var(--surface)] p-10 text-center"><h3 className="font-display text-2xl font-extrabold">O palco está vazio por enquanto.</h3><p className="mt-2 text-slate-600">Crie seu primeiro evento e comece a receber inscrições.</p></div>}</div></main>;
}
